### ISSUE TITLE
New remix project, no action works

### ISSUE THREAD

**Issue by ItamarShDev** [Code-Forge-Net/Remix-Forge#25]
Using remix on Node v20 with Bun.

All actions result in 
```log 
[error] TypeError: Cannot read properties of undefined (reading 'path')
	at Ig.joinPath (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:58607)
	at t.generateRouteFile (/Users/itamarsharify/.vscode/extensions/codeforge.remix-forge-0.5.4/dist/extension.js:1:45968)
	at async T0.h (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32837) remix-forge.generateRemixRoute {"value":"CodeForge.remix-forge","_lower":"codeforge.remix-forge"}
```

**Comment by FDiskas** [comment]
And this happens on windows pc only right?

**Comment by ItamarShDev** [comment]
I am using MacOS
both intel and M1 Pro
